# Generated by Django 6.0.6 on 2026-07-22 21:47

import django.db.models.deletion
import supply_offers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_customercashtransaction_idempotency_hash_and_more'),
        ('daily_journal', '0006_journaltransaction_electronic_reference_and_more'),
        ('inventory', '0003_alter_inventorymovement_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('counter_offered', 'New Price Proposed'), ('customer_accepted', 'Customer Accepted'), ('customer_declined', 'Customer Declined'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('awaiting_receipt', 'Awaiting Product Receipt'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('customer_reference', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('detailed_address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('customer_safe_admin_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='SDG', max_length=10)),
                ('proposed_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('admin_proposed_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('agreed_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('receipt_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('payment_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_supply_offers', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_offers', to='customers.customer')),
                ('linked_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_offer_payments', to='daily_journal.journaltransaction')),
                ('linked_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_offer_payments', to='customers.customercashtransaction')),
                ('payment_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_supply_offers', to=settings.AUTH_USER_MODEL)),
                ('receipt_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_supply_offers', to=settings.AUTH_USER_MODEL)),
                ('receiving_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_offers', to='inventory.warehouse')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_supply_offers', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_supply_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyOfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('customer_proposed_unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('customer_proposed_line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('admin_proposed_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('agreed_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('agreed_line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('accepted_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('rejected_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('quality_grade', models.CharField(blank=True, max_length=120)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('packaging_details', models.CharField(blank=True, max_length=255)),
                ('item_notes', models.TextField(blank=True)),
                ('product_name_snapshot', models.CharField(max_length=100)),
                ('unit_snapshot', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supply_offers.supplyoffer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_offer_items', to='inventory.product')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_offer_items', to='inventory.productunit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyOfferAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('product_image', 'Product Image'), ('quality_document', 'Quality Document'), ('other_document', 'Other Document')], default='product_image', max_length=30)),
                ('file', models.FileField(upload_to=supply_offers.models.supply_offer_attachment_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='supply_offers.supplyoffer')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_supply_offer_attachments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='supply_offers.supplyofferitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyOfferStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('actor_type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('customer_safe_note', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_offer_status_changes', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='supply_offers.supplyoffer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supplyoffer',
            index=models.Index(fields=['offer_number'], name='supply_offe_offer_n_48ad79_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyoffer',
            index=models.Index(fields=['customer', 'status'], name='supply_offe_custome_320699_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyoffer',
            index=models.Index(fields=['status'], name='supply_offe_status_bc59f2_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyoffer',
            index=models.Index(fields=['city'], name='supply_offe_city_5bfa66_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyoffer',
            index=models.Index(fields=['submitted_at'], name='supply_offe_submitt_2484e0_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyoffer',
            index=models.Index(fields=['idempotency_key'], name='supply_offe_idempot_4565a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplyoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('customer', 'idempotency_key'), name='unique_customer_supply_offer_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='supplyofferitem',
            constraint=models.UniqueConstraint(fields=('offer', 'product', 'product_unit'), name='unique_supply_offer_product_unit_line'),
        ),
        migrations.AddConstraint(
            model_name='supplyofferitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='supply_offer_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplyofferitem',
            constraint=models.CheckConstraint(condition=models.Q(('customer_proposed_unit_price__gt', 0)), name='supply_offer_item_price_positive'),
        ),
        migrations.AddIndex(
            model_name='supplyofferattachment',
            index=models.Index(fields=['offer'], name='supply_offe_offer_i_9710bc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyofferattachment',
            index=models.Index(fields=['attachment_type'], name='supply_offe_attachm_fffb29_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyofferstatushistory',
            index=models.Index(fields=['offer', 'created_at'], name='supply_offe_offer_i_3424a2_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyofferstatushistory',
            index=models.Index(fields=['new_status'], name='supply_offe_new_sta_2955a0_idx'),
        ),
    ]
