# Generated by Django 6.0.6 on 2026-07-23 16:20

import django.db.models.deletion
import supply_offers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customercashtransaction_source_type'),
        ('daily_journal', '0007_alter_journaltransaction_source_type'),
        ('inventory', '0003_alter_inventorymovement_source_type'),
        ('supply_offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyoffer',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplyoffer',
            name='payment_status',
            field=models.CharField(default='not_paid', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplyoffer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('counter_offered', 'New Price Proposed'), ('customer_accepted', 'Customer Accepted'), ('customer_declined', 'Customer Declined'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('awaiting_receipt', 'Awaiting Product Receipt'), ('paid', 'Paid'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('response_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending_customer', 'Pending Customer'), ('accepted_by_customer', 'Accepted by Customer'), ('rejected_by_customer', 'Rejected by Customer'), ('withdrawn_by_admin', 'Withdrawn by Admin'), ('expired', 'Expired'), ('superseded', 'Superseded'), ('final_approved', 'Final Approved')], default='pending_customer', max_length=30)),
                ('customer_safe_message', models.TextField(blank=True)),
                ('proposed_receipt_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer_responded_at', models.DateTimeField(blank=True, null=True)),
                ('customer_rejection_reason', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('proposed_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_offer_responses', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='supply_offers.supplyoffer')),
                ('proposed_receiving_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_offer_responses', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-response_version'],
            },
        ),
        migrations.CreateModel(
            name='OfferResponseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_proposed_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('admin_proposed_unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('admin_proposed_line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_items', to='supply_offers.supplyofferitem')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supply_offers.offerresponse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OfferPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_of_khartoum', 'Bank of Khartoum Transfer'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=30)),
                ('payment_date', models.DateField()),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('paying_bank', models.CharField(blank=True, max_length=120)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to=supply_offers.models.supply_offer_attachment_path)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('confirmed', 'Confirmed'), ('reversed', 'Reversed'), ('failed', 'Failed')], default='recorded', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_offer_payments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_payments', to='customers.customer')),
                ('linked_customer_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_payments', to='customers.customercashtransaction')),
                ('linked_journal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_payments', to='daily_journal.journaltransaction')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_payments', to='supply_offers.supplyoffer')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_offer_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_number'], name='supply_offe_payment_ab6c86_idx'), models.Index(fields=['offer'], name='supply_offe_offer_i_65504d_idx'), models.Index(fields=['customer'], name='supply_offe_custome_9b8707_idx'), models.Index(fields=['payment_method'], name='supply_offe_payment_79281c_idx'), models.Index(fields=['idempotency_key'], name='supply_offe_idempot_306d7e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='offer_payment_amount_positive'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('offer', 'idempotency_key'), name='unique_offer_payment_idempotency')],
            },
        ),
        migrations.AddIndex(
            model_name='offerresponse',
            index=models.Index(fields=['offer', 'is_current'], name='supply_offe_offer_i_68ff90_idx'),
        ),
        migrations.AddIndex(
            model_name='offerresponse',
            index=models.Index(fields=['status'], name='supply_offe_status_cecbc8_idx'),
        ),
        migrations.AddIndex(
            model_name='offerresponse',
            index=models.Index(fields=['idempotency_key'], name='supply_offe_idempot_5ea894_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerresponse',
            constraint=models.UniqueConstraint(fields=('offer', 'response_version'), name='unique_offer_response_version'),
        ),
        migrations.AddConstraint(
            model_name='offerresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('offer', 'idempotency_key'), name='unique_offer_response_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='offerresponseitem',
            constraint=models.UniqueConstraint(fields=('response', 'offer_item'), name='unique_response_offer_item'),
        ),
        migrations.AddConstraint(
            model_name='offerresponseitem',
            constraint=models.CheckConstraint(condition=models.Q(('admin_proposed_quantity__gt', 0)), name='offer_response_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='offerresponseitem',
            constraint=models.CheckConstraint(condition=models.Q(('admin_proposed_unit_price__gt', 0)), name='offer_response_item_price_positive'),
        ),
    ]
