# Generated by Django 6.0.6 on 2026-07-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_offers', '0002_supplyoffer_paid_amount_supplyoffer_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerresponse',
            name='customer_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyoffer',
            name='latest_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
