# Generated by Django 6.0.6 on 2026-07-21 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_product_created_by_product_deleted_at_and_more'),
        ('invoices', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ready_for_shipment', 'Ready for Shipment'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ready_for_shipment', max_length=30)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('vehicle_number', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_shipments', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_shipments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='customers.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='invoices.invoice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='orders.order')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code_snapshot', models.CharField(max_length=20)),
                ('product_name_en_snapshot', models.CharField(max_length=100)),
                ('product_name_ar_snapshot', models.CharField(max_length=100)),
                ('unit_snapshot', models.CharField(max_length=20)),
                ('requested_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('number_of_bags', models.PositiveIntegerField(blank=True, null=True)),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('average_bag_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='invoices.invoiceitem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='inventory.product')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='inventory.productunit')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['shipment_number'], name='shipments_s_shipmen_8b3960_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order'], name='shipments_s_order_i_38988b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['invoice'], name='shipments_s_invoice_1f4625_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['customer'], name='shipments_s_custome_4b802e_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipments_s_created_1bef45_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('invoice',), name='unique_active_shipment_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment', 'invoice_item'), name='unique_shipment_invoice_item'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='shipment_item_requested_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('actual_quantity__gt', 0), ('actual_quantity__isnull', True), _connector='OR'), name='shipment_item_actual_quantity_positive_or_null'),
        ),
    ]
