# Generated by Django 6.0.6 on 2026-07-21 04:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


PRODUCT_SEEDS = [
    ('PROD-001', 'White Sesame', 'سمسم أبيض', 'commodity', ['Qintar']),
    ('PROD-002', 'Red Sesame', 'سمسم أحمر', 'commodity', ['Qintar']),
    ('PROD-003', 'Corn', 'ذرة', 'commodity', ['KG', 'Bag']),
    ('PROD-004', 'Dabara', 'دبارة', 'supply', ['Bale', 'Unit']),
    ('PROD-005', 'Sacks / Khaysh', 'خيش / جوالات', 'supply', ['Bale', 'Unit']),
    ('PROD-006', 'Plastic', 'بلاستيك', 'supply', ['Bale', 'Unit']),
]


def seed_products_and_units(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    ProductUnit = apps.get_model('inventory', 'ProductUnit')
    for code, name_en, name_ar, category, units in PRODUCT_SEEDS:
        product, _ = Product.objects.update_or_create(
            code=code,
            defaults={'name_en': name_en, 'name_ar': name_ar, 'category': category, 'is_active': True},
        )
        for index, unit in enumerate(units):
            ProductUnit.objects.get_or_create(product=product, unit=unit, defaults={'is_default': index == 0})


def unseed_products_and_units(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Product.objects.filter(code__in=[seed[0] for seed in PRODUCT_SEEDS]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('commodity', 'Commodity'), ('supply', 'Supply')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('warehouse_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('capacity_unit', models.CharField(choices=[('Qintar', 'Qintar'), ('KG', 'KG'), ('Bag', 'Bag'), ('Bale', 'Bale'), ('Unit', 'Unit')], max_length=20)),
                ('manager_name', models.CharField(max_length=150)),
                ('guard_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_warehouses', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_warehouses', to=settings.AUTH_USER_MODEL)),
                ('primary_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_warehouses', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['warehouse_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('stock_in', 'Stock In'), ('manual_withdrawal', 'Manual Withdrawal'), ('shipment_out', 'Shipment Out'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit', models.CharField(choices=[('Qintar', 'Qintar'), ('KG', 'KG'), ('Bag', 'Bag'), ('Bale', 'Bale'), ('Unit', 'Unit')], max_length=20)),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=18)),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=18)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('shipment', 'Shipment'), ('transfer', 'Transfer'), ('system', 'System')], default='manual', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('unit', models.CharField(choices=[('Qintar', 'Qintar'), ('KG', 'KG'), ('Bag', 'Bag'), ('Bale', 'Bale'), ('Unit', 'Unit')], max_length=20)),
                ('minimum_threshold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['product__name_en'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('Qintar', 'Qintar'), ('KG', 'KG'), ('Bag', 'Bag'), ('Bale', 'Bale'), ('Unit', 'Unit')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.product')),
            ],
            options={
                'ordering': ['product__name_en', 'unit'],
                'constraints': [models.UniqueConstraint(fields=('product', 'unit'), name='unique_product_unit')],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['warehouse_name'], name='inventory_w_warehou_909090_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['location'], name='inventory_w_locatio_02629e_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_deleted'], name='inventory_w_is_dele_c5fc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='inventory_w_is_acti_3ddeac_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='warehouse_capacity_positive'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['warehouse'], name='inventory_i_warehou_a68d46_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product'], name='inventory_i_product_2153f2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type'], name='inventory_i_movemen_e5f549_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['created_at'], name='inventory_i_created_75a91c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['source_type'], name='inventory_i_source__e2a8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['source_reference'], name='inventory_i_source__88d2f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='movement_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_before__gte', 0)), name='movement_before_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_after__gte', 0)), name='movement_after_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product', 'unit'), name='unique_warehouse_product_unit'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_threshold__gte', 0)), name='inventory_threshold_non_negative'),
        ),
        migrations.RunPython(seed_products_and_units, unseed_products_and_units),
    ]
