# Generated by Django 6.0.6 on 2026-07-21 06:06

import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


SEED_CODE_RENAMES = {
    'PROD-001': 'PRD-0001',
    'PROD-002': 'PRD-0002',
    'PROD-003': 'PRD-0003',
    'PROD-004': 'PRD-0004',
    'PROD-005': 'PRD-0005',
    'PROD-006': 'PRD-0006',
}


def normalize_seed_product_codes(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    for old_code, new_code in SEED_CODE_RENAMES.items():
        Product.objects.filter(code=old_code).update(code=new_code)


def restore_seed_product_codes(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    for old_code, new_code in SEED_CODE_RENAMES.items():
        Product.objects.filter(code=new_code).update(code=old_code)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productunit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='minimum_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='productunit',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='productunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(normalize_seed_product_codes, restore_seed_product_codes),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='inventory_p_code_a06c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name_en'], name='inventory_p_name_en_224616_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name_ar'], name='inventory_p_name_ar_aba7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_b457a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='inventory_p_is_acti_47a270_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_deleted'], name='inventory_p_is_dele_1f66ff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='inventory_p_created_081871_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name_en'), condition=models.Q(('is_deleted', False)), name='unique_active_product_name_en_ci'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name_ar'), condition=models.Q(('is_deleted', False)), name='unique_active_product_name_ar_ci'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='product_unit_purchase_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='product_unit_selling_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_selling_price__gte', 0), ('minimum_selling_price__isnull', True), _connector='OR'), name='product_unit_minimum_price_non_negative'),
        ),
    ]
