# Generated by Django 6.0.6 on 2026-07-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_created_by_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('daily_journal', 'Daily Journal'), ('shipment', 'Shipment'), ('transfer', 'Transfer'), ('system', 'System')], default='manual', max_length=20),
        ),
    ]
