# Generated by Django 6.0.6 on 2026-07-21 05:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_journal', '0003_journaltransaction_payment_method_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('secondary_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('customer_type', models.CharField(choices=[('farmer', 'Farmer'), ('investor', 'Investor'), ('consumer', 'Consumer'), ('exporter', 'Exporter'), ('factory', 'Factory'), ('supplier', 'Supplier')], max_length=20)),
                ('photo', models.FileField(blank=True, null=True, upload_to='customers/')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_customers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('opening_debt', 'Opening Debt'), ('opening_credit', 'Opening Credit'), ('payment_received', 'Payment Received'), ('payment_owed', 'Payment Owed'), ('customer_expense', 'Customer Expense'), ('invoice_charge', 'Invoice Charge'), ('adjustment_debit', 'Adjustment Debit'), ('adjustment_credit', 'Adjustment Credit')], max_length=30)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField()),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('customer', 'Customer'), ('invoice', 'Invoice'), ('system', 'System')], default='manual', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_customer_cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('linked_journal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_cash_transactions', to='daily_journal.journaltransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCommodityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('product_received', 'Product Received'), ('product_delivered', 'Product Delivered'), ('product_stored', 'Product Stored'), ('warehouse_withdrawal', 'Warehouse Withdrawal')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit', models.CharField(max_length=20)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('description', models.TextField()),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('inventory', 'Inventory'), ('shipment', 'Shipment'), ('system', 'System')], default='manual', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_commodity_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commodity_transactions', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_customer_commodity_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_commodity_transactions', to='inventory.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_commodity_transactions', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['code'], name='customers_c_code_4fafda_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='customers_c_custome_47da94_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_deleted'], name='customers_c_is_dele_3ef12f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('phone',), name='unique_active_customer_phone'),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['customer'], name='customers_c_custome_1fdde5_idx'),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['transaction_type'], name='customers_c_transac_1f5dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['payment_method'], name='customers_c_payment_a7fe38_idx'),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['created_at'], name='customers_c_created_c16fda_idx'),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['source_type'], name='customers_c_source__5dec0d_idx'),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['source_reference'], name='customers_c_source__b999a2_idx'),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['is_deleted'], name='customers_c_is_dele_b9b09d_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='customer_cash_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='customercommoditytransaction',
            index=models.Index(fields=['customer'], name='customers_c_custome_22a987_idx'),
        ),
        migrations.AddIndex(
            model_name='customercommoditytransaction',
            index=models.Index(fields=['product'], name='customers_c_product_1d4162_idx'),
        ),
        migrations.AddIndex(
            model_name='customercommoditytransaction',
            index=models.Index(fields=['unit'], name='customers_c_unit_010841_idx'),
        ),
        migrations.AddIndex(
            model_name='customercommoditytransaction',
            index=models.Index(fields=['transaction_type'], name='customers_c_transac_a12112_idx'),
        ),
        migrations.AddIndex(
            model_name='customercommoditytransaction',
            index=models.Index(fields=['created_at'], name='customers_c_created_e9215f_idx'),
        ),
        migrations.AddIndex(
            model_name='customercommoditytransaction',
            index=models.Index(fields=['source_type'], name='customers_c_source__edab55_idx'),
        ),
        migrations.AddIndex(
            model_name='customercommoditytransaction',
            index=models.Index(fields=['source_reference'], name='customers_c_source__f30160_idx'),
        ),
        migrations.AddIndex(
            model_name='customercommoditytransaction',
            index=models.Index(fields=['is_deleted'], name='customers_c_is_dele_83d9f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercommoditytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='customer_commodity_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='customercommoditytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_value__gte', 0), ('estimated_value__isnull', True), _connector='OR'), name='customer_commodity_estimated_value_non_negative'),
        ),
    ]
