# Generated by Django 6.0.6 on 2026-07-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customeraccount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customeraccount',
            new_name='customers_c_user_id_d49120_idx',
            old_name='customers_c_user_id_856e31_idx',
        ),
        migrations.RenameIndex(
            model_name='customeraccount',
            new_name='customers_c_custome_812eb1_idx',
            old_name='customers_c_custome_03d238_idx',
        ),
    ]
