# Generated by Django 6.0.6 on 2026-07-21 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_customers_c_user_id_856e31_idx_customers_c_user_id_d49120_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=60)),
                ('key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_idempotency_keys', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'operation', 'key'], name='customers_m_custome_2fa53e_idx'), models.Index(fields=['created_at'], name='customers_m_created_37e3f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'operation', 'key'), name='unique_mobile_customer_idempotency_key')],
            },
        ),
    ]
