# Generated by Django 6.0.6 on 2026-07-22 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_mobileidempotencykey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='customers_c_user_id_2af164_idx'), models.Index(fields=['expires_at'], name='customers_c_expires_54f347_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('secondary_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('customer_type', models.CharField(choices=[('farmer', 'Farmer'), ('investor', 'Investor'), ('consumer', 'Consumer'), ('exporter', 'Exporter'), ('factory', 'Factory'), ('supplier', 'Supplier')], max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_code_hash', models.CharField(blank=True, max_length=255)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('last_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('email_verification_pending', 'Email Verification Pending'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='email_verification_pending', max_length=40)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_customer_registrations', to=settings.AUTH_USER_MODEL)),
                ('created_customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to='customers.customer')),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_registration_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='customers_c_email_78c16c_idx'), models.Index(fields=['phone'], name='customers_c_phone_a51eaa_idx'), models.Index(fields=['status'], name='customers_c_status_82b1d4_idx'), models.Index(fields=['created_at'], name='customers_c_created_703bff_idx')],
            },
        ),
    ]
