# Generated by Django 6.0.6 on 2026-07-22 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customerpasswordresetrequest_and_more'),
        ('daily_journal', '0004_journaltransaction_daily_journ_source__3da6c4_idx_and_more'),
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customercashtransaction',
            name='idempotency_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customercashtransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customercashtransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_cash_transactions', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='customercashtransaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customercashtransaction',
            name='payment_purpose',
            field=models.CharField(blank=True, choices=[('invoice_payment', 'Invoice Payment'), ('previous_balance', 'Previous Balance Payment'), ('advance_payment', 'Advance Payment'), ('general_account_payment', 'General Account Payment'), ('other', 'Other')], max_length=40),
        ),
        migrations.AddField(
            model_name='customercashtransaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customercashtransaction',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customercashtransaction',
            name='reversal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_originals', to='customers.customercashtransaction'),
        ),
        migrations.AddField(
            model_name='customercashtransaction',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercashtransaction',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_customer_cash_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['reference_number'], name='customers_c_referen_12f94d_idx'),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['payment_purpose'], name='customers_c_payment_179f58_idx'),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['invoice'], name='customers_c_invoice_b03e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['idempotency_key'], name='customers_c_idempot_6da3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='customercashtransaction',
            index=models.Index(fields=['is_reversed'], name='customers_c_is_reve_fcbad1_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercashtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('customer', 'idempotency_key'), name='unique_customer_payment_idempotency_key'),
        ),
    ]
