# Generated by Django 6.0.6 on 2026-07-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customercashtransaction_idempotency_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercashtransaction',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('customer', 'Customer'), ('invoice', 'Invoice'), ('system', 'System'), ('offer_payment', 'Offer Payment')], default='manual', max_length=20),
        ),
    ]
