# Generated by Django 6.0.6 on 2026-07-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customercashtransaction_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregistrationrequest',
            name='verification_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerregistrationrequest',
            name='verification_resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
