# Generated by Django 6.0.6 on 2026-07-21 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_journal', '0003_journaltransaction_payment_method_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('secondary_phone', models.CharField(blank=True, max_length=30)),
                ('worker_type', models.CharField(choices=[('general_worker', 'General Worker'), ('bag_carrying_worker', 'Bag Carrying Worker'), ('weighing_worker', 'Weighing Worker')], max_length=30)),
                ('assigned_work', models.CharField(max_length=255)),
                ('default_daily_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('default_price_per_bag', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='workers/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('working', 'Working'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workers', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_workers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_workers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('calculation_method', models.CharField(choices=[('daily_wage', 'Daily Wage'), ('bag_based', 'Bag Based')], max_length=20)),
                ('number_of_bags', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('price_per_bag', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('daily_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_wage', models.DecimalField(decimal_places=2, max_digits=18)),
                ('work_description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('weighing', 'Weighing'), ('shipment', 'Shipment'), ('system', 'System')], default='manual', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_worker_work_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_worker_work_records', to=settings.AUTH_USER_MODEL)),
                ('linked_journal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker_work_records', to='daily_journal.journaltransaction')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_worker_work_records', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_work_records', to='inventory.warehouse')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_records', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['code'], name='workers_wor_code_7ef0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['phone'], name='workers_wor_phone_d58763_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['worker_type'], name='workers_wor_worker__cf7bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['status'], name='workers_wor_status_c1a993_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['is_active'], name='workers_wor_is_acti_bfc83b_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['is_deleted'], name='workers_wor_is_dele_dc1626_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['created_at'], name='workers_wor_created_b762bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('phone',), name='unique_active_worker_phone'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.CheckConstraint(condition=models.Q(('default_daily_wage__gt', 0), ('default_daily_wage__isnull', True), _connector='OR'), name='worker_default_daily_wage_positive'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.CheckConstraint(condition=models.Q(('default_price_per_bag__gt', 0), ('default_price_per_bag__isnull', True), _connector='OR'), name='worker_default_price_per_bag_positive'),
        ),
        migrations.AddIndex(
            model_name='workerworkrecord',
            index=models.Index(fields=['code'], name='workers_wor_code_ec481f_idx'),
        ),
        migrations.AddIndex(
            model_name='workerworkrecord',
            index=models.Index(fields=['worker'], name='workers_wor_worker__7d338b_idx'),
        ),
        migrations.AddIndex(
            model_name='workerworkrecord',
            index=models.Index(fields=['warehouse'], name='workers_wor_warehou_d2770a_idx'),
        ),
        migrations.AddIndex(
            model_name='workerworkrecord',
            index=models.Index(fields=['calculation_method'], name='workers_wor_calcula_c29d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='workerworkrecord',
            index=models.Index(fields=['payment_status'], name='workers_wor_payment_2963e1_idx'),
        ),
        migrations.AddIndex(
            model_name='workerworkrecord',
            index=models.Index(fields=['payment_method'], name='workers_wor_payment_da7475_idx'),
        ),
        migrations.AddIndex(
            model_name='workerworkrecord',
            index=models.Index(fields=['created_at'], name='workers_wor_created_c61258_idx'),
        ),
        migrations.AddIndex(
            model_name='workerworkrecord',
            index=models.Index(fields=['source_type'], name='workers_wor_source__e83648_idx'),
        ),
        migrations.AddIndex(
            model_name='workerworkrecord',
            index=models.Index(fields=['source_reference'], name='workers_wor_source__90aef2_idx'),
        ),
        migrations.AddIndex(
            model_name='workerworkrecord',
            index=models.Index(fields=['is_deleted'], name='workers_wor_is_dele_0456df_idx'),
        ),
        migrations.AddConstraint(
            model_name='workerworkrecord',
            constraint=models.CheckConstraint(condition=models.Q(('total_wage__gt', 0)), name='worker_work_total_wage_positive'),
        ),
        migrations.AddConstraint(
            model_name='workerworkrecord',
            constraint=models.CheckConstraint(condition=models.Q(('daily_wage__gt', 0), ('daily_wage__isnull', True), _connector='OR'), name='worker_work_daily_wage_positive'),
        ),
        migrations.AddConstraint(
            model_name='workerworkrecord',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_bags__gt', 0), ('number_of_bags__isnull', True), _connector='OR'), name='worker_work_bags_positive'),
        ),
        migrations.AddConstraint(
            model_name='workerworkrecord',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_bag__gt', 0), ('price_per_bag__isnull', True), _connector='OR'), name='worker_work_price_per_bag_positive'),
        ),
    ]
