# Generated by Django 6.0.6 on 2026-07-21 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_type', models.CharField(choices=[('cash', 'Cash'), ('commodity', 'Commodity')], max_length=20)),
                ('party', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('invoice', 'Invoice'), ('shipment', 'Shipment'), ('warehouse', 'Warehouse'), ('customer', 'Customer'), ('worker', 'Worker')], default='manual', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cash_type', models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('commodity_direction', models.CharField(blank=True, choices=[('lahu', 'Lahu'), ('alayh', 'Alayh')], max_length=20, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_journal_transactions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_journal_transactions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_journal_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['journal_type'], name='daily_journ_journal_f1df02_idx'), models.Index(fields=['created_at'], name='daily_journ_created_18276f_idx'), models.Index(fields=['cash_type'], name='daily_journ_cash_ty_01e5c2_idx'), models.Index(fields=['product_name'], name='daily_journ_product_95cd15_idx'), models.Index(fields=['is_deleted'], name='daily_journ_is_dele_dfae71_idx'), models.Index(fields=['journal_type', 'created_at'], name='daily_journ_journal_2dab0d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('amount__isnull', True), _connector='OR'), name='journal_amount_positive_or_null'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('quantity__isnull', True), _connector='OR'), name='journal_quantity_positive_or_null'), models.CheckConstraint(condition=models.Q(('estimated_value__gte', 0), ('estimated_value__isnull', True), _connector='OR'), name='journal_estimated_value_non_negative_or_null')],
            },
        ),
    ]
