# Generated by Django 6.0.6 on 2026-07-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journaltransaction',
            name='commodity_direction',
        ),
    ]
