# Generated by Django 6.0.6 on 2026-07-21 03:45

from django.conf import settings
from django.db import migrations, models


def set_existing_cash_payment_method(apps, schema_editor):
    JournalTransaction = apps.get_model('daily_journal', 'JournalTransaction')
    JournalTransaction.objects.filter(journal_type='cash', payment_method__isnull=True).update(payment_method='cash')


def clear_existing_cash_payment_method(apps, schema_editor):
    JournalTransaction = apps.get_model('daily_journal', 'JournalTransaction')
    JournalTransaction.objects.filter(journal_type='cash', payment_method='cash').update(payment_method=None)


class Migration(migrations.Migration):

    dependencies = [
        ('daily_journal', '0002_remove_journaltransaction_commodity_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journaltransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20, null=True),
        ),
        migrations.RunPython(set_existing_cash_payment_method, clear_existing_cash_payment_method),
        migrations.AddIndex(
            model_name='journaltransaction',
            index=models.Index(fields=['payment_method'], name='daily_journ_payment_6e35ec_idx'),
        ),
    ]
