# Generated by Django 6.0.6 on 2026-07-22 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_journal', '0003_journaltransaction_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journaltransaction',
            index=models.Index(fields=['source_type', 'source_reference'], name='daily_journ_source__3da6c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='journaltransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reference', ''), _negated=True), fields=('source_type', 'source_reference'), name='unique_journal_source_reference'),
        ),
    ]
