# Generated by Django 6.0.6 on 2026-07-22 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_journal', '0004_journaltransaction_daily_journ_source__3da6c4_idx_and_more'),
        ('inventory', '0003_alter_inventorymovement_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journaltransaction',
            name='idempotency_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='linked_inventory_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_transaction', to='inventory.inventorymovement'),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='reversal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_originals', to='daily_journal.journaltransaction'),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_journal_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_transactions', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='warehouse_operation',
            field=models.CharField(blank=True, choices=[('stock_in', 'Add Stock'), ('manual_withdrawal', 'Manual Withdrawal')], max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='journaltransaction',
            index=models.Index(fields=['warehouse_operation'], name='daily_journ_warehou_68804f_idx'),
        ),
        migrations.AddIndex(
            model_name='journaltransaction',
            index=models.Index(fields=['warehouse'], name='daily_journ_warehou_f484fa_idx'),
        ),
        migrations.AddIndex(
            model_name='journaltransaction',
            index=models.Index(fields=['idempotency_key'], name='daily_journ_idempot_150676_idx'),
        ),
        migrations.AddIndex(
            model_name='journaltransaction',
            index=models.Index(fields=['is_reversed'], name='daily_journ_is_reve_d7cca1_idx'),
        ),
        migrations.AddConstraint(
            model_name='journaltransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('created_by', 'idempotency_key'), name='unique_journal_user_idempotency_key'),
        ),
    ]
