# Generated by Django 6.0.6 on 2026-07-22 19:30

from django.db import migrations, models


def online_to_electronic(apps, schema_editor):
    JournalTransaction = apps.get_model('daily_journal', 'JournalTransaction')
    JournalTransaction.objects.filter(payment_method='online').update(payment_method='electronic')


def electronic_to_online(apps, schema_editor):
    JournalTransaction = apps.get_model('daily_journal', 'JournalTransaction')
    JournalTransaction.objects.filter(payment_method='electronic').update(payment_method='online')


class Migration(migrations.Migration):

    dependencies = [
        ('daily_journal', '0005_journaltransaction_idempotency_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaltransaction',
            name='electronic_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='daily_journal/receipts/'),
        ),
        migrations.AlterField(
            model_name='journaltransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('electronic', 'Electronic Payment')], max_length=20, null=True),
        ),
        migrations.RunPython(online_to_electronic, electronic_to_online),
    ]
