# Generated by Django 6.0.6 on 2026-07-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_journal', '0006_journaltransaction_electronic_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltransaction',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('invoice', 'Invoice'), ('shipment', 'Shipment'), ('warehouse', 'Warehouse'), ('customer', 'Customer'), ('worker', 'Worker'), ('offer_payment', 'Offer Payment')], default='manual', max_length=20),
        ),
    ]
